### ISSUE TITLE
Yaml output is only adding the first Uniform in a UniformBlock

### ISSUE THREAD

**Issue by Interrupt** [floooh/sokol-tools#145]
When building shaders using the Yaml mode, the resulting Yaml file only includes the first uniform in the uniform array in uniform_blocks. Issue shown here:

The uniform block in the shader glsl file:
```
uniform vs_params {
    mat4 u_projViewMatrix;
    mat4 u_modelMatrix;
    vec4 u_color;
};
```

The uniform block in the Yaml file:
```
          uniform_blocks:
            -
              slot: 0
              size: 144
              struct_name: vs_params
              inst_name: _16
              uniforms:
                -
                  name: u_projViewMatrix
                  type: vec4
                  array_count: 4
                  offset: 0
```

**Comment by Interrupt** [comment]
Ah, this looks related to https://github.com/floooh/sokol-tools/pull/143 which was merged recently.

It would still be nice to include all the variables in a uniform block, for Material systems it seems almost required to know the sizing and ordering of all the uniforms.

**Comment by Interrupt** [comment]
If I turn off flattening in `reflection.cc` by changing:
```194:        refl_ub.flattened = false;```

It outputs what I expect. Is there a reason this isn't the default? Output after that change:

```
uniform_blocks:
  -
    slot: 0
    size: 144
    struct_name: vs_params
    inst_name: _19
    uniforms:
      -
        name: u_projViewMatrix
        type: mat4
        array_count: 0
        offset: 0
      -
        name: u_modelMatrix
        type: mat4
        array_count: 0
        offset: 64
      -
        name: u_color
        type: vec4
        array_count: 0
        offset: 128
```

**Comment by floooh** [comment]
The previous behaviour that the first uniform is exported was indeed a bug.

Flattened uniform blocks only require a single glUniform call for the whole uniform block instead of one glUniform call per uniform block member, so it's much more efficient. This is only relevant for GL backends though, D3D11 and Metal generally only use the uniform block size and don't care about the interior.

The reflection info is intended to be consumed directly by sokol_gfx.h, using the reflection info for tools like material editors wasn't a goal.

Currently the only way to get reflection information about uniform block interiors is via the `--reflection` cmdline argument, this will create C functions which allow to query the offset and type of a uniform in a uniform block (you'll need to know the names upfront though...).

In the C generator this is implemented here:

https://github.com/floooh/sokol-tools/blob/9ca922eb3176689e81a702a711fdc2b9e53addf5/src/shdc/generators/sokolc.cc#L485-L539

...all the other generators (including the yaml generator here: https://github.com/floooh/sokol-tools/blob/master/src/shdc/generators/yaml.cc) don't implement those runtime reflection code generators. I guess it would be somewhat trivial to add to the yaml generator though by (more or less) copy-pasting the methods from the C generator.

PR welcome ;)

**Comment by Interrupt** [comment]
Thanks! I'll take a crack at adding the reflection info to the YAML output - and maybe for Zig as well.

**Comment by floooh** [comment]
...so just a quick braindump when you start working on it:

...when you look at the YamlGenerator.cc, this looks quite different than the other generators in that it overrides the top-level `generate()` method:

https://github.com/floooh/sokol-tools/blob/0201c6103096305d5b6ea6400066bd063f0a0c44/src/shdc/generators/yaml.cc#L14-L113

 Regular generators don't do that and instead depend on '2nd-level-methods' being called from the parent class Generator::generate() method, which defines a top-level structure for the generated code:

https://github.com/floooh/sokol-tools/blob/0201c6103096305d5b6ea6400066bd063f0a0c44/src/shdc/generators/generator.cc#L11-L34

...since the YamlGenerator overrides this top-level method with its own implementation, you have a free hand about how the output yaml file will be structured (e.g. where you place that additional info).

The only restriction is that you shouldn't change the existing structure and names, and instead extend the original format with reflection info.

I'm not sure what a good structure would look like, but maybe just add a `members:` item at the same level as `uniforms`?

E.g. currently it looks like this:

```yaml
          uniform_blocks:
            -
              slot: 0
              size: 32
              struct_name: light_params
              inst_name: _467
              uniforms:
                -
                  name: light_params
                  type: vec4
                  array_count: 2
                  offset: 0
```

...maybe this makes sense?

```yaml
          uniform_blocks:
            -
              slot: 0
              size: 32
              struct_name: vs_params
              inst_name: _467
              uniforms:
                -
                  name: vs_params
                  type: vec4
                  array_count: 4
                  offset: 0
              members:
                -
                  name: u_projViewMatrix
                  type: mat4
                  array_count: 0
                  offset: 0
                -
                  name: u_modelMatrix
                  type: mat4
                  array_count: 0
                  offset: 64
                -
                  name: u_color
                  type: vec4
                  array_count: 0
                  offset: 128
```
